import sys

class ISO3166:
    """
        A Class to convert between formats of the ISO3166 standard
    """

    def __init__(self):
        #Declare main table : contains a list of [ NAME, FLAG ]
        self.alfa2 = {
            "AF":["Afghanistan","🇦🇫"],
            "AL":["Albania","🇦🇱"],
            "DZ":["Algeria","🇩🇿"],
            "AS":["American Samoa",""],
            "AD":["Andorra","🇦🇩"],
            "AO":["Angola","🇦🇴"],
            "AI":["Anguilla","🇦🇮"],
            "AQ":["Antarctica","🇦🇶"],
            "AG":["Antigua and Barbuda","🇦🇬"],
            "AR":["Argentina","🇦🇷"],
            "AM":["Armenia","🇦🇲"],
            "AW":["Aruba","🇦🇼"],
            "AU":["Australia","🇦🇺"],
            "AT":["Austria","🇦🇹"],
            "AZ":["Azerbaijan","🇦🇿"],
            "BS":["Bahamas","🇧🇸"],
            "BH":["Bahrain","🇧🇭"],
            "BD":["Bangladesh","🇧🇩"],
            "BB":["Barbados","🇧🇧"],
            "BY":["Belarus","🇧🇾"],
            "BE":["Belgium","🇧🇪"],
            "BZ":["Belize","🇧🇿"],
            "BJ":["Benin","🇧🇯"],
            "BM":["Bermuda","🇧🇲"],
            "BT":["Bhutan","🇧🇹"],
            "BO":["Bolivia","🇧🇴"],
            "BQ":["Bonaire, Sint Eustatius and Saba","🇧🇶‍"],
            "BA":["Bosnia and Herzegovina","🇧🇦"],
            "BW":["Botswana","🇧🇼"],
            "BV":["Bouvet Island","🇧🇻"],
            "BR":["Brazil","🇧🇷"],
            "IO":["British Indian Ocean Territory","🇮🇴"],
            "BN":["Brunei Darussalam","🇧🇳"],
            "BG":["Bulgaria","🇧🇬"],
            "BF":["Burkina Faso","🇧🇫"],
            "BI":["Burundi","🇧🇮"],
            "CV":["Cabo Verde","🇨🇻"],
            "KH":["Cambodia","🇰🇭"],
            "CM":["Cameroon","🇨🇲"],
            "CA":["Canada","🇨🇦"],
            "KY":["Cayman Islands","🇰🇾"],
            "CF":["Central African Republic","🇨🇫"],
            "TD":["Chad","🇹🇩"],
            "CL":["Chile","🇨🇱"],
            "CN":["China","🇨🇳"],
            "CX":["Christmas Island","🇨🇽"],
            "CC":["Cocos (Keeling) Islands","🇨🇨"],
            "CO":["Colombia","🇨🇴"],
            "KM":["Comoros","🇰🇲"],
            "CD":["Democratic Republic of the Congo","🇨🇩"],
            "CG":["Congo","🇨🇬"],
            "CK":["Cook Islands","🇨🇰"],
            "CR":["Costa Rica","🇨🇷"],
            "HR":["Croatia","🇭🇷"],
            "CU":["Cuba","🇨🇺"],
            "CW":["Curaçao","🇨🇼"],
            "CY":["Cyprus","🇨🇾"],
            "CZ":["Czechia","🇨🇿"],
            "CI":["Côte d`Ivoire","🇨🇮"],
            "DK":["Denmark","🇩🇰"],
            "DJ":["Djibouti","🇩🇯"],
            "DM":["Dominica","🇩🇲"],
            "DO":["Dominican Republic","🇩🇴"],
            "EC":["Ecuador","🇪🇨"],
            "EG":["Egypt","🇪🇬"],
            "SV":["El Salvador","🇸🇻"],
            "GQ":["Equatorial Guinea","🇬🇶"],
            "ER":["Eritrea","🇪🇷"],
            "EE":["Estonia","🇪🇪"],
            "SZ":["Eswatini","🇸🇿"],
            "ET":["Ethiopia","🇪🇹"],
            "FK":["Falkland Islands","🇫🇰"],
            "FO":["Faroe Islands","🇫🇴"],
            "FJ":["Fiji","🇫🇯"],
            "FI":["Finland","🇫🇮"],
            "FR":["France","🇫🇷"],
            "GF":["French Guiana","🇬🇫"],
            "PF":["French Polynesia","🇵🇫"],
            "TF":["French Southern Territories","🇹🇫"],
            "GA":["Gabon","🇬🇦"],
            "GM":["Gambia","🇬🇲"],
            "GE":["Georgia","🇬🇪"],
            "DE":["Germany","🇩🇪"],
            "GH":["Ghana","🇬🇭"],
            "GI":["Gibraltar","🇬🇮"],
            "GR":["Greece","🇬🇷"],
            "GL":["Greenland","🇬🇱"],
            "GD":["Grenada","🇬🇩"],
            "GP":["Guadeloupe","🇬🇵"],
            "GU":["Guam","🇬🇺"],
            "GT":["Guatemala","🇬🇹"],
            "GG":["Guernsey","🇬🇬"],
            "GN":["Guinea","🇬🇳"],
            "GW":["Guinea-Bissau","🇬🇼"],
            "GY":["Guyana","🇬🇾"],
            "HT":["Haiti","🇭🇹"],
            "HM":["Heard Island and McDonald Islands","🇭🇲"],
            "VA":["Holy See","🇻🇦"],
            "HN":["Honduras","🇭🇳"],
            "HK":["Hong Kong","🇭🇰"],
            "HU":["Hungary","🇭🇺"],
            "IS":["Iceland","🇮🇸"],
            "IN":["India","🇮🇳"],
            "ID":["Indonesia","🇮🇩"],
            "IR":["Iran","🇮🇷"],
            "IQ":["Iraq","🇮🇶"],
            "IE":["Ireland","🇮🇪"],
            "IM":["Isle of Man","🇮🇲"],
            "IL":["Israel","🇮🇱"],
            "IT":["Italy","🇮🇹"],
            "JM":["Jamaica","🇯🇲"],
            "JP":["Japan","🇯🇵"],
            "JE":["Jersey","🇯🇪"],
            "JO":["Jordan","🇯🇴"],
            "KZ":["Kazakhstan","🇰🇿"],
            "KE":["Kenya","🇰🇪"],
            "KI":["Kiribati","🇰🇮"],
            "KP":["Democratic People`s Republic of Korea","🇰🇵"],
            "KR":["Republic of Korea","🇰🇷"],
            "KW":["Kuwait","🇰🇼"],
            "KG":["Kyrgyzstan","🇰🇬"],
            "LA":["People`s Democratic Republic of Lao","🇱🇦"],
            "LV":["Latvia","🇱🇻"],
            "LB":["Lebanon","🇱🇧"],
            "LS":["Lesotho","🇱🇸"],
            "LR":["Liberia","🇱🇷"],
            "LY":["Libya","🇱🇾"],
            "LI":["Liechtenstein","🇱🇮"],
            "LT":["Lithuania","🇱🇹"],
            "LU":["Luxembourg","🇱🇺"],
            "MO":["Macao","🇲🇴"],
            "MG":["Madagascar","🇲🇬"],
            "MW":["Malawi","🇲🇼"],
            "MY":["Malaysia","🇲🇾"],
            "MV":["Maldives","🇲🇻"],
            "ML":["Mali","🇲🇱"],
            "MT":["Malta","🇲🇹"],
            "MH":["Marshall Islands","🇲🇭"],
            "MQ":["Martinique","🇲🇶"],
            "MR":["Mauritania","🇲🇷"],
            "MU":["Mauritius","🇲🇺"],
            "YT":["Mayotte","🇾🇹"],
            "MX":["Mexico","🇲🇽"],
            "FM":["Micronesia","🇫🇲"],
            "MD":["Moldova","🇲🇩"],
            "MC":["Monaco","🇲🇨"],
            "MN":["Mongolia","🇲🇳"],
            "ME":["Montenegro","🇲🇪"],
            "MS":["Montserrat","🇲🇸"],
            "MA":["Morocco","🇲🇦"],
            "MZ":["Mozambique","🇲🇿"],
            "MM":["Myanmar","🇲🇲"],
            "NA":["Namibia","🇳🇦"],
            "NR":["Nauru","🇳🇷"],
            "NP":["Nepal","🇳🇵"],
            "NL":["Netherlands","🇳🇱"],
            "NC":["New Caledonia","🇳🇨"],
            "NZ":["New Zealand","🇳🇿"],
            "NI":["Nicaragua","🇳🇮"],
            "NE":["Niger","🇳🇪"],
            "NG":["Nigeria","🇳🇬"],
            "NU":["Niue","🇳🇺"],
            "NF":["Norfolk Island","🇳🇫"],
            "MP":["Northern Mariana Islands","🇲🇵"],
            "NO":["Norway","🇳🇴"],
            "OM":["Oman","🇴🇲"],
            "PK":["Pakistan","🇵🇰"],
            "PW":["Palau","🇵🇼"],
            "PS":["Palestine, State of","🇵🇸"],
            "PA":["Panama","🇵🇦"],
            "PG":["Papua New Guinea","🇵🇬"],
            "PY":["Paraguay","🇵🇾"],
            "PE":["Peru","🇵🇪"],
            "PH":["Philippines","🇵🇭"],
            "PN":["Pitcairn","🇵🇳"],
            "PL":["Poland","🇵🇱"],
            "PT":["Portugal","🇵🇹"],
            "PR":["Puerto Rico","🇵🇷"],
            "QA":["Qatar","🇶🇦"],
            "MK":["Republic of North Macedonia","🇲🇰"],
            "RO":["Romania","🇷🇴"],
            "RU":["Russian Federation","🇷🇺"],
            "RW":["Rwanda","🇷🇼"],
            "RE":["Réunion","🇷🇪"],
            "BL":["Saint Barthélemy","🇧🇱"],
            "SH":["Saint Helena, Ascension and Tristan da Cunha","🇹🇦"],
            "KN":["Saint Kitts and Nevis","🇰🇳"],
            "LC":["Saint Lucia","🇱🇨"],
            "MF":["Saint Martin","🇲🇫"],
            "PM":["Saint Pierre and Miquelon","🇵🇲"],
            "VC":["Saint Vincent and the Grenadines","🇻🇨"],
            "WS":["Samoa","🇼🇸"],
            "SM":["San Marino","🇸🇲"],
            "ST":["Sao Tome and Principe","🇸🇹"],
            "SA":["Saudi Arabia","🇸🇦"],
            "SN":["Senegal","🇸🇳"],
            "RS":["Serbia","🇷🇸"],
            "SC":["Seychelles","🇸🇨"],
            "SL":["Sierra Leone","🇸🇱"],
            "SG":["Singapore","🇸🇬"],
            "SX":["Sint Maarten","🇸🇽"],
            "SK":["Slovakia","🇸🇰"],
            "SI":["Slovenia","🇸🇮"],
            "SB":["Solomon Islands","🇸🇧"],
            "SO":["Somalia","🇸🇴"],
            "ZA":["South Africa","🇿🇦"],
            "GS":["South Georgia and the South Sandwich Islands","🇬🇸"],
            "SS":["South Sudan","🇸🇸"],
            "ES":["Spain","🇪🇸"],
            "LK":["Sri Lanka","🇱🇰"],
            "SD":["Sudan","🇸🇩"],
            "SR":["Suriname","🇸🇷"],
            "SJ":["Svalbard and Jan Mayen","🇸🇯"],
            "SE":["Sweden","🇸🇪"],
            "CH":["Switzerland","🇨🇭"],
            "SY":["Syrian Arab Republic","🇸🇾"],
            "TW":["Taiwan","🇹🇼"],
            "TJ":["Tajikistan","🇹🇯"],
            "TZ":["United Republic of Tanzania","🇹🇿"],
            "TH":["Thailand","🇹🇭"],
            "TL":["Timor-Leste","🇹🇱"],
            "TG":["Togo","🇹🇬"],
            "TK":["Tokelau","🇹🇰"],
            "TO":["Tonga","🇹🇴"],
            "TT":["Trinidad and Tobago","🇹🇹"],
            "TN":["Tunisia","🇹🇳"],
            "TR":["Turkey","🇹🇷"],
            "TM":["Turkmenistan","🇹🇲"],
            "TC":["Turks and Caicos Islands","🇹🇨"],
            "TV":["Tuvalu","🇹🇻"],
            "UG":["Uganda","🇺🇬"],
            "UA":["Ukraine","🇺🇦"],
            "AE":["United Arab Emirates","🇦🇪"],
            "GB":["United Kingdom of Great Britain and Northern Ireland","🇬🇧"],
            "UM":["United States Minor Outlying Islands","🇺🇲"],
            "US":["United States of America","🇺🇸"],
            "UY":["Uruguay","🇺🇾"],
            "UZ":["Uzbekistan","🇺🇿"],
            "VU":["Vanuatu","🇻🇺"],
            "VE":["Venezuela","🇻🇪"],
            "VN":["Viet Nam","🇻🇳"],
            "VG":["British Virgin Islands","🇻🇬"],
            "VI":["US Virgin Islands","🇻🇮"],
            "WF":["Wallis and Futuna","🇼🇫"],
            "EH":["Western Sahara","🇪🇭"],
            "YE":["Yemen","🇾🇪"],
            "ZM":["Zambia","🇿🇲"],
            "ZW":["Zimbabwe","🇿🇼"],
            "AX":["Åland Islands","🇦🇽"]
        }

        #Declare a table to convert from numeric to alfa2
        self.numeric = {
            "004":"AF",
            "008":"AL",
            "012":"DZ",
            "016":"AS",
            "020":"AD",
            "024":"AO",
            "660":"AI",
            "010":"AQ",
            "028":"AG",
            "032":"AR",
            "051":"AM",
            "533":"AW",
            "036":"AU",
            "040":"AT",
            "031":"AZ",
            "044":"BS",
            "048":"BH",
            "050":"BD",
            "052":"BB",
            "112":"BY",
            "056":"BE",
            "084":"BZ",
            "204":"BJ",
            "060":"BM",
            "064":"BT",
            "068":"BO",
            "535":"BQ",
            "070":"BA",
            "072":"BW",
            "074":"BV",
            "076":"BR",
            "086":"IO",
            "096":"BN",
            "100":"BG",
            "854":"BF",
            "108":"BI",
            "132":"CV",
            "116":"KH",
            "120":"CM",
            "124":"CA",
            "136":"KY",
            "140":"CF",
            "148":"TD",
            "152":"CL",
            "156":"CN",
            "162":"CX",
            "166":"CC",
            "170":"CO",
            "174":"KM",
            "180":"CD",
            "178":"CG",
            "184":"CK",
            "188":"CR",
            "191":"HR",
            "192":"CU",
            "531":"CW",
            "196":"CY",
            "203":"CZ",
            "384":"CI",
            "208":"DK",
            "262":"DJ",
            "212":"DM",
            "214":"DO",
            "218":"EC",
            "818":"EG",
            "222":"SV",
            "226":"GQ",
            "232":"ER",
            "233":"EE",
            "748":"SZ",
            "231":"ET",
            "238":"FK",
            "234":"FO",
            "242":"FJ",
            "246":"FI",
            "250":"FR",
            "254":"GF",
            "258":"PF",
            "260":"TF",
            "266":"GA",
            "270":"GM",
            "268":"GE",
            "276":"DE",
            "288":"GH",
            "292":"GI",
            "300":"GR",
            "304":"GL",
            "308":"GD",
            "312":"GP",
            "316":"GU",
            "320":"GT",
            "831":"GG",
            "324":"GN",
            "624":"GW",
            "328":"GY",
            "332":"HT",
            "334":"HM",
            "336":"VA",
            "340":"HN",
            "344":"HK",
            "348":"HU",
            "352":"IS",
            "356":"IN",
            "360":"ID",
            "364":"IR",
            "368":"IQ",
            "372":"IE",
            "833":"IM",
            "376":"IL",
            "380":"IT",
            "388":"JM",
            "392":"JP",
            "832":"JE",
            "400":"JO",
            "398":"KZ",
            "404":"KE",
            "296":"KI",
            "408":"KP",
            "410":"KR",
            "414":"KW",
            "417":"KG",
            "418":"LA",
            "428":"LV",
            "422":"LB",
            "426":"LS",
            "430":"LR",
            "434":"LY",
            "438":"LI",
            "440":"LT",
            "442":"LU",
            "446":"MO",
            "450":"MG",
            "454":"MW",
            "458":"MY",
            "462":"MV",
            "466":"ML",
            "470":"MT",
            "584":"MH",
            "474":"MQ",
            "478":"MR",
            "480":"MU",
            "175":"YT",
            "484":"MX",
            "583":"FM",
            "498":"MD",
            "492":"MC",
            "496":"MN",
            "499":"ME",
            "500":"MS",
            "504":"MA",
            "508":"MZ",
            "104":"MM",
            "516":"NA",
            "520":"NR",
            "524":"NP",
            "528":"NL",
            "540":"NC",
            "554":"NZ",
            "558":"NI",
            "562":"NE",
            "566":"NG",
            "570":"NU",
            "574":"NF",
            "580":"MP",
            "578":"NO",
            "512":"OM",
            "586":"PK",
            "585":"PW",
            "275":"PS",
            "591":"PA",
            "598":"PG",
            "600":"PY",
            "604":"PE",
            "608":"PH",
            "612":"PN",
            "616":"PL",
            "620":"PT",
            "630":"PR",
            "634":"QA",
            "807":"MK",
            "642":"RO",
            "643":"RU",
            "646":"RW",
            "638":"RE",
            "652":"BL",
            "654":"SH",
            "659":"KN",
            "662":"LC",
            "663":"MF",
            "666":"PM",
            "670":"VC",
            "882":"WS",
            "674":"SM",
            "678":"ST",
            "682":"SA",
            "686":"SN",
            "688":"RS",
            "690":"SC",
            "694":"SL",
            "702":"SG",
            "534":"SX",
            "703":"SK",
            "705":"SI",
            "090":"SB",
            "706":"SO",
            "710":"ZA",
            "239":"GS",
            "728":"SS",
            "724":"ES",
            "144":"LK",
            "729":"SD",
            "740":"SR",
            "744":"SJ",
            "752":"SE",
            "756":"CH",
            "760":"SY",
            "158":"TW",
            "762":"TJ",
            "834":"TZ",
            "764":"TH",
            "626":"TL",
            "768":"TG",
            "772":"TK",
            "776":"TO",
            "780":"TT",
            "788":"TN",
            "792":"TR",
            "795":"TM",
            "796":"TC",
            "798":"TV",
            "800":"UG",
            "804":"UA",
            "784":"AE",
            "826":"GB",
            "581":"UM",
            "840":"US",
            "858":"UY",
            "860":"UZ",
            "548":"VU",
            "862":"VE",
            "704":"VN",
            "092":"VG",
            "850":"VI",
            "876":"WF",
            "732":"EH",
            "887":"YE",
            "894":"ZM",
            "716":"ZW",
            "248":"AX"
        }

        #Declare a table to convert between alfa3 and alfa2
        self.alfa3 = {
            "AFG":"AF",
            "ALB":"AL",
            "DZA":"DZ",
            "ASM":"AS",
            "AND":"AD",
            "AGO":"AO",
            "AIA":"AI",
            "ATA":"AQ",
            "ATG":"AG",
            "ARG":"AR",
            "ARM":"AM",
            "ABW":"AW",
            "AUS":"AU",
            "AUT":"AT",
            "AZE":"AZ",
            "BHS":"BS",
            "BHR":"BH",
            "BGD":"BD",
            "BRB":"BB",
            "BLR":"BY",
            "BEL":"BE",
            "BLZ":"BZ",
            "BEN":"BJ",
            "BMU":"BM",
            "BTN":"BT",
            "BOL":"BO",
            "BES":"BQ",
            "BIH":"BA",
            "BWA":"BW",
            "BVT":"BV",
            "BRA":"BR",
            "IOT":"IO",
            "BRN":"BN",
            "BGR":"BG",
            "BFA":"BF",
            "BDI":"BI",
            "CPV":"CV",
            "KHM":"KH",
            "CMR":"CM",
            "CAN":"CA",
            "CYM":"KY",
            "CAF":"CF",
            "TCD":"TD",
            "CHL":"CL",
            "CHN":"CN",
            "CXR":"CX",
            "CCK":"CC",
            "COL":"CO",
            "COM":"KM",
            "COD":"CD",
            "COG":"CG",
            "COK":"CK",
            "CRI":"CR",
            "HRV":"HR",
            "CUB":"CU",
            "CUW":"CW",
            "CYP":"CY",
            "CZE":"CZ",
            "CIV":"CI",
            "DNK":"DK",
            "DJI":"DJ",
            "DMA":"DM",
            "DOM":"DO",
            "ECU":"EC",
            "EGY":"EG",
            "SLV":"SV",
            "GNQ":"GQ",
            "ERI":"ER",
            "EST":"EE",
            "SWZ":"SZ",
            "ETH":"ET",
            "FLK":"FK",
            "FRO":"FO",
            "FJI":"FJ",
            "FIN":"FI",
            "FRA":"FR",
            "GUF":"GF",
            "PYF":"PF",
            "ATF":"TF",
            "GAB":"GA",
            "GMB":"GM",
            "GEO":"GE",
            "DEU":"DE",
            "GHA":"GH",
            "GIB":"GI",
            "GRC":"GR",
            "GRL":"GL",
            "GRD":"GD",
            "GLP":"GP",
            "GUM":"GU",
            "GTM":"GT",
            "GGY":"GG",
            "GIN":"GN",
            "GNB":"GW",
            "GUY":"GY",
            "HTI":"HT",
            "HMD":"HM",
            "VAT":"VA",
            "HND":"HN",
            "HKG":"HK",
            "HUN":"HU",
            "ISL":"IS",
            "IND":"IN",
            "IDN":"ID",
            "IRN":"IR",
            "IRQ":"IQ",
            "IRL":"IE",
            "IMN":"IM",
            "ISR":"IL",
            "ITA":"IT",
            "JAM":"JM",
            "JPN":"JP",
            "JEY":"JE",
            "JOR":"JO",
            "KAZ":"KZ",
            "KEN":"KE",
            "KIR":"KI",
            "PRK":"KP",
            "KOR":"KR",
            "KWT":"KW",
            "KGZ":"KG",
            "LAO":"LA",
            "LVA":"LV",
            "LBN":"LB",
            "LSO":"LS",
            "LBR":"LR",
            "LBY":"LY",
            "LIE":"LI",
            "LTU":"LT",
            "LUX":"LU",
            "MAC":"MO",
            "MDG":"MG",
            "MWI":"MW",
            "MYS":"MY",
            "MDV":"MV",
            "MLI":"ML",
            "MLT":"MT",
            "MHL":"MH",
            "MTQ":"MQ",
            "MRT":"MR",
            "MUS":"MU",
            "MYT":"YT",
            "MEX":"MX",
            "FSM":"FM",
            "MDA":"MD",
            "MCO":"MC",
            "MNG":"MN",
            "MNE":"ME",
            "MSR":"MS",
            "MAR":"MA",
            "MOZ":"MZ",
            "MMR":"MM",
            "NAM":"NA",
            "NRU":"NR",
            "NPL":"NP",
            "NLD":"NL",
            "NCL":"NC",
            "NZL":"NZ",
            "NIC":"NI",
            "NER":"NE",
            "NGA":"NG",
            "NIU":"NU",
            "NFK":"NF",
            "MNP":"MP",
            "NOR":"NO",
            "OMN":"OM",
            "PAK":"PK",
            "PLW":"PW",
            "PSE":"PS",
            "PAN":"PA",
            "PNG":"PG",
            "PRY":"PY",
            "PER":"PE",
            "PHL":"PH",
            "PCN":"PN",
            "POL":"PL",
            "PRT":"PT",
            "PRI":"PR",
            "QAT":"QA",
            "MKD":"MK",
            "ROU":"RO",
            "RUS":"RU",
            "RWA":"RW",
            "REU":"RE",
            "BLM":"BL",
            "SHN":"SH",
            "KNA":"KN",
            "LCA":"LC",
            "MAF":"MF",
            "SPM":"PM",
            "VCT":"VC",
            "WSM":"WS",
            "SMR":"SM",
            "STP":"ST",
            "SAU":"SA",
            "SEN":"SN",
            "SRB":"RS",
            "SYC":"SC",
            "SLE":"SL",
            "SGP":"SG",
            "SXM":"SX",
            "SVK":"SK",
            "SVN":"SI",
            "SLB":"SB",
            "SOM":"SO",
            "ZAF":"ZA",
            "SGS":"GS",
            "SSD":"SS",
            "ESP":"ES",
            "LKA":"LK",
            "SDN":"SD",
            "SUR":"SR",
            "SJM":"SJ",
            "SWE":"SE",
            "CHE":"CH",
            "SYR":"SY",
            "TWN":"TW",
            "TJK":"TJ",
            "TZA":"TZ",
            "THA":"TH",
            "TLS":"TL",
            "TGO":"TG",
            "TKL":"TK",
            "TON":"TO",
            "TTO":"TT",
            "TUN":"TN",
            "TUR":"TR",
            "TKM":"TM",
            "TCA":"TC",
            "TUV":"TV",
            "UGA":"UG",
            "UKR":"UA",
            "ARE":"AE",
            "GBR":"GB",
            "UMI":"UM",
            "USA":"US",
            "URY":"UY",
            "UZB":"UZ",
            "VUT":"VU",
            "VEN":"VE",
            "VNM":"VN",
            "VGB":"VG",
            "VIR":"VI",
            "WLF":"WF",
            "ESH":"EH",
            "YEM":"YE",
            "ZMB":"ZM",
            "ZWE":"ZW",
            "ALA":"AX"
        }

    def get_alfa2( self, tmpCode ):
        #Return the list declared above taking an alfa2 code
        return self.alfa2[ tmpCode ]

    def get_alfa3( self, tmpCode ):
        #Return the list declared above taking an alfa3 code
        return self.alfa2[ self.alfa3[ tmpCode ] ]

    def get_numeric( self, tmpCode ):
        #Return the list declared above taking an numeric code
        return self.alfa2[ self.numeric[ tmpCode ] ]

    def convert_alfa2_alfa3( self, tmpCode ):
        #Iterate over the 3/2 table
        for tmpAlfa3, tmpAlfa2 in self.alfa3.items():
            #Is the code the one we are searching for?
            if tmpAlfa2 == tmpCode:
                #YES - Return the alfa2 code
                return tmpAlfa3
        #Return None because we haven't found a match
        return None

    def convert_alfa2_numeric( self, tmpCode ):
        #Iterate over the numeric table
        for tmpNumeric, tmpAlfa2 in self.numeric.items():
            #Is the code the one we are searching for?
            if tmpAlfa2 == tmpCode:
                #YES - Return the alfa2 code
                return tmpNumeric
        #Return None because we haven't found a match
        return None

    def convert_alfa3_numeric( self, tmpCode ):
        tmpAlfa2 = self.convert_alfa3_alfa2( tmpCode )
        if tmpAlfa2 != None :
            return self.convert_alfa2_numeric( tmpAlfa2 )
        else:
            return None
    def convert_alfa3_alfa2( self, tmpCode ):
        #Iterate over the 3/2 table
        for tmpAlfa3, tmpAlfa2 in self.alfa3.items():
            #Is the code the one we are searching for?
            if tmpAlfa3 == tmpCode:
                #YES - Return the alfa2 code
                return tmpAlfa2
        #Return None because we haven't found a match
        return None

    def convert_numeric_alfa2( self, tmpCode ):
        #Iterate over the numeric table
        for tmpNumeric, tmpAlfa2 in self.numeric.items():
            #Is the code the one we are searching for?
            if tmpNumeric == tmpCode:
                #YES - Return the alfa2 code
                return tmpAlfa2
        #Return None because we haven't found a match
        return None

    def convert_numeric_alfa3( self, tmpCode ):
        tmpAlfa2 = self.convert_numeric_alfa2( tmpCode )
        if tmpAlfa2 != None :
            return self.convert_alfa2_alfa3( tmpAlfa2 )
        else:
            return None

if __name__ == '__main__':
    #Unit Test
    #Provide the valid codes as parameters at the command line to test the correctness
    if len(sys.argv)>1:
        tmpTest = ISO3166()
        print( "Test information:" )
        print( " Code2   " + str( tmpTest.get_alfa2( sys.argv[1] ) ) )
        print( " 2->3    " + str( tmpTest.convert_alfa2_alfa3( sys.argv[1] ) ) )
        print( " 2->N    " + str( tmpTest.convert_alfa2_numeric( sys.argv[1] ) ) )
        print( " Code3   " + str( tmpTest.get_alfa3( sys.argv[2] ) ) )
        print( " 3->2    " + str( tmpTest.convert_alfa3_alfa2( sys.argv[2] ) ) )
        print( " 3->N    " + str( tmpTest.convert_alfa3_numeric( sys.argv[2] ) ) )
        print( " Numeric " + str( tmpTest.get_numeric( sys.argv[3] ) ) )
        print( " N->2    " + str( tmpTest.convert_numeric_alfa2( sys.argv[3] ) ) )
        print( " N->3    " + str( tmpTest.convert_numeric_alfa3( sys.argv[3] ) ) )
